name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --features tokio
      - name: clippy
        run: cargo clippy --all-targets --features tokio -- -D warnings
      - name: Run tests
        run: cargo test --features tokio --verbose
